<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE tarjeta [
    <!ELEMENT tarjeta (numero, titular, fechaVencimiento, tipo, entidadEmisora)>
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT titular (#PCDATA)>
    <!ELEMENT fechaVencimiento (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT entidadEmisora (#PCDATA)>
]>

<tarjeta>
    <numero>123456789</numero>
    <titular>Ana Gonzales</titular>
    <fechaVencimiento>2029-12</fechaVencimiento>
    <tipo>Visa</tipo>
    <entidadEmisora>BBVA</entidadEmisora>
</tarjeta>