<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE gestionNotas [
  <!ELEMENT gestionNotas (alumno)> 

  <!ELEMENT alumno (nombre, apellidos, curso, asignatura+)> 
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apellidos (#PCDATA)>
  <!ELEMENT curso (#PCDATA)>
  
  <!ELEMENT asignatura (titulo, trimestre1, trimestre2, trimestre3)> 
  <!ELEMENT titulo (#PCDATA)> 
  <!ELEMENT trimestre1 (#PCDATA)>
  <!ELEMENT trimestre2 (#PCDATA)>
  <!ELEMENT trimestre3 (#PCDATA)>


]>

<gestionNotas>
    <alumno>
        <nombre>Nombre1</nombre>
        <apellidos>Apellidos</apellidos>
        <curso>1º DAW</curso>
        <asignatura>
            <titulo>Programación</titulo>
            <trimestre1>3.0</trimestre1>
            <trimestre2>5.0</trimestre2>
            <trimestre3>9</trimestre3>
        </asignatura>
        <asignatura>
            <titulo>Base de Datos</titulo>
            <trimestre1>7.5</trimestre1>
            <trimestre2>3.0</trimestre2>
            <trimestre3>7.8</trimestre3>
        </asignatura>
        <asignatura>
            <titulo>Entornos de Desarrollo</titulo>
            <trimestre1>9.2</trimestre1>
            <trimestre2>9.0</trimestre2>
            <trimestre3>9.0</trimestre3>
        </asignatura>
        <asignatura>
            <titulo>Sistemas</titulo>
            <trimestre1>8.0</trimestre1>
            <trimestre2>9.6</trimestre2>
            <trimestre3>9.7</trimestre3>
        </asignatura>
     
                
    </alumno>

    <piepagina>
        <p>Alejandro Borrego </p>
    </piepagina>
</gestionNotas>