<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="ejercicio1.css"?> 

<!DOCTYPE catalogo [
    <!ELEMENT catalogo (libro+)>
    <!ELEMENT libro (titulo, autor, editorial, anio, genero,paginas,precio,portada,resumen)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
    <!ELEMENT anio (#PCDATA)>
    <!ELEMENT genero (#PCDATA)>
    <!ELEMENT paginas (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT portada (#PCDATA)>
    <!ATTLIST portada foto CDATA #REQUIRED>
    <!ELEMENT resumen (#PCDATA)>
    <!ENTITY estado "agotado">
]>

<catalogo>
<libro>
<titulo>Nosotros</titulo>
<autor>Zamiatin</autor>
<editorial>Editorial 1</editorial>
<anio>año: 1920</anio>
<genero>Género: Distópico</genero>
<paginas>Pág: 210</paginas>
<precio>10€</precio>
<portada foto="nosotros"></portada>
<resumen></resumen>

</libro>

<libro>
<titulo>En nombre del viento</titulo>
<autor>Patrik</autor>
<editorial>Editorial 2</editorial>
<anio>1999</anio>
<genero>Fantasía</genero>
<paginas>800</paginas>
<precio>15€</precio>
<portada foto="viento"></portada>
<resumen></resumen>
</libro>


</catalogo>
